### ISSUE TITLE
Getting keyboardProxy results in crash

### ISSUE THREAD

**Issue by daverix** [udevbe/wayland-java-bindings#8]
I have copied and modified the example in the repo. When I'm trying to add events for keyboard I get the following error:

```
Got an exception, This is most likely a bug.
Method=public void net.daverix.wayland.core.Window.enter(org.freedesktop.wayland.client.WlKeyboardProxy,int,org.freedesktop.wayland.client.WlSurfaceProxy,java.nio.ByteBuffer), implementation=net.daverix.wayland.core.Window@27f8302d, arguments=[org.freedesktop.wayland.client.WlKeyboardProxy@6422c665, 110257, org.freedesktop.wayland.client.WlSurfaceProxy@6422c525, null], message=@org.freedesktop.wayland.util.Message(signature=uoa, types=[int, class org.freedesktop.wayland.client.WlSurfaceProxy, class java.nio.ByteBuffer], since=1, functionName=enter, name=enter)
java.lang.IllegalArgumentException: Can not convert wl_argument type: a
    at org.freedesktop.wayland.util.Dispatcher.fromArgument(Dispatcher.java:104)
    at org.freedesktop.wayland.util.Dispatcher.apply(Dispatcher.java:169)
    at org.freedesktop.wayland.client.jna.WaylandClientLibrary.wl_display_dispatch(Native Method)
    at org.freedesktop.wayland.client.Display.dispatch(Display.java:132)
    at net.daverix.wayland.core.DefaultDisplay.dispatch(DefaultDisplay.java:126)
    at net.daverix.wayland.core.Application.main(Application.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Here's my application class:

```
package net.daverix.wayland.core;

import java.io.IOException;

public class Application {


    public static void main(String[] args) {
        Display display = new DefaultDisplay();
        Window window = new Window(display, 250, 250);

        display.onCreate();
        try {
            window.onCreate();
            window.redraw(0);

            int state;
            do {
                state = display.dispatch();
            } while (state != -1);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            window.onDestroy();
            display.onDestroy();
        }
    }
}
```

My DefaultDisplay class provides methods instead of getters to follow "law of demeter":

```
public class DefaultDisplay implements WlRegistryEvents, Display {
    private WlDisplayProxy display;
    private WlCompositorProxy compositor;
    private WlRegistryProxy registry;
    private WlShellProxy shell;
    private WlSeatProxy seat;
    private WlShmProxy shm;
    private int shmFormats = 0;

    @Override
    public void onCreate() {
        display = WlDisplayProxy.connect("wayland-0");
        if (!display.isValid()) {
            System.out.println("Display not valid!");
            return;
        }

        registry = display.getRegistry(this);
        display.roundtrip();
        display.roundtrip();
    }

    ...

    @Override
    public WlKeyboardProxy createKeyboard(WlKeyboardEventsV4 events) {
        if(seat == null) throw new IllegalStateException("seat not available");

        return seat.getKeyboard(events);
    }

    @Override
    public void global(WlRegistryProxy emitter, int name, @Nonnull String interfaceName, int version) {
        System.out.println(String.format("Got a registry event for %s id %d", interfaceName, name));

        switch (interfaceName) {
            case WlCompositorProxy.INTERFACE_NAME:
                this.compositor = this.registry.<WlCompositorEvents, WlCompositorProxy>bind(name,
                        WlCompositorProxy.class, WlCompositorEventsV3.VERSION, new WlCompositorEventsV3() {
                        });
                break;
            case WlShmProxy.INTERFACE_NAME:
                this.shm = this.registry.<WlShmEvents, WlShmProxy>bind(name,
                        WlShmProxy.class,
                        WlShmEvents.VERSION,
                        new WlShmEvents() {
                            @Override
                            public void format(final WlShmProxy emitter,
                                               final int format) {
                                DefaultDisplay.this.shmFormats |= (1 << format);
                            }
                        });
                break;
            case WlShellProxy.INTERFACE_NAME:
                this.shell = this.registry.<WlShellEvents, WlShellProxy>bind(name,
                        WlShellProxy.class,
                        WlShellEvents.VERSION,
                        new WlShellEvents() {
                        });
                break;
            case WlSeatProxy.INTERFACE_NAME:
                this.seat = this.registry.<WlSeatEvents, WlSeatProxy>bind(name,
                        WlSeatProxy.class,
                        WlSeatEventsV4.VERSION,
                        new WlSeatEventsV4() {
                            @Override
                            public void capabilities(final WlSeatProxy emitter,
                                                     final int capabilities) {
                                System.out.printf("Got capabilities %d%n", capabilities);
                            }

                            @Override
                            public void name(final WlSeatProxy emitter,
                                             @Nonnull final String name) {
                                System.out.printf("Got seat with name %s%n", name);
                            }
                        });
                break;
        }
    }

    @Override
    public void globalRemove(WlRegistryProxy emitter, int name) {
        System.out.println(String.format("Got a registry losing event for %d", name));
    }
```

The Window class looks like this (mostly the same):

```
public class Window implements WlSurfaceEventsV3, WlRegionEvents, WlShellSurfaceEvents, WlPointerEventsV3, WlKeyboardEventsV4 {
    private static final int BTN_LEFT  = 0x110;
    private static final int BTN_RIGHT = 0x111;

    private final Display display;
    private int width;
    private int height;
    private BufferPool bufferPool;
    private WlSurfaceProxy surface;
    private WlRegionProxy region;
    private WlShellSurfaceProxy shellSurface;
    private WlPointerProxy pointer;
    private WlKeyboardProxy keyboard;
    private WlCallbackProxy callback;
    private boolean needsBufferPoolUpdate;
    private int edges;
    private int pendingHeight;
    private int pendingWidth;
    private int pointerX;
    private int pointerY;

    public Window(Display display,
                  final int width,
                  final int height) {
        this.display = display;
        this.width = width;
        this.height = height;
    }

    public void onCreate() throws IOException {
        this.bufferPool = createBufferPool(2);
        this.surface = this.display.createSurface(this);
        this.region = this.display.createRegion(this);
        this.surface.setInputRegion(region);
        this.shellSurface = this.display.createShellSurface(this, this.surface);
        this.pointer = this.display.createPointer(this);
        this.keyboard = this.display.createKeyboard(this);

        this.surface.damage(0, 0, this.width, this.height);
        this.region.add(0, 0, this.width, this.height);
    }

    ...
}
```

**Comment by Zubnix** [comment]
Yup that's a bug. Looks like I forgot to map array types on the wire protocol. whoopsly doodly.

**Comment by daverix** [comment]
WIth the latest commit in master (4d1bb651), i now get this error instead:

```
java.lang.IllegalArgumentException: argument type mismatch
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.freedesktop.wayland.util.Dispatcher.apply(Dispatcher.java:185)
    at org.freedesktop.wayland.client.jna.WaylandClientLibrary.wl_display_dispatch(Native Method)
    at org.freedesktop.wayland.client.Display.dispatch(Display.java:132)
    at examples.SimpleShm.main(SimpleShm.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

My code can be found here: https://github.com/daverix/wayland-java-bindings/tree/keyboard

**Comment by Zubnix** [comment]
Yes that's another bug I found while fixing the original issue. Expect a fix somewhere later today. See #12
